added changes for Network Tokenization
CyberSource/cybersource-rest-samples-php pull request #63
Opened 2023-07-31 04:34 UTC by monu-kumar-visa

2023-07-31 04:35 UTC, monu-kumar-visa commented on composer.json
> +    "repositories" : [
Will remove this

2023-08-01 06:57 UTC, gaubansa commented on composer.lock
don't add lock file

2023-08-02 10:17 UTC, gnongsie requested changes

2023-08-02 10:17 UTC, gnongsie commented on Resources/ExternalConfiguration.php
> +        $this -> jwePEMFileDirectory = "Resources/NetworkTokenCert.pem";
Check if space is allowed before and after `->`

2023-08-02 10:20 UTC, gnongsie approved these changes

2023-09-13 11:34 UTC, gaubansa approved these changes

2023-11-20 08:03 UTC, merged